#include <Arduino.h>
#include "usb_compat.h"

// Undefine the macros so we can access the real usbd_class_driver_t and define usbd_app_driver_get_cb
#undef usbd_class_driver_t
#undef usbd_app_driver_get_cb

// Declare the unused callback function generated by audio-tools
extern "C" usbd_class_driver_compat_t const* usbd_app_driver_get_cb_unused(uint8_t* count);

// Implement the real usbd_app_driver_get_cb that TinyUSB expects
extern "C" usbd_class_driver_t const* usbd_app_driver_get_cb(uint8_t* count) {
    auto* compat = usbd_app_driver_get_cb_unused(count);
    if (!compat) {
        return nullptr;
    }

    static usbd_class_driver_t real_driver;

    #if CFG_TUSB_DEBUG >= CFG_TUD_LOG_LEVEL
    real_driver.name = compat->name;
    #endif

    real_driver.init = compat->init;
    real_driver.reset = compat->reset;
    real_driver.open = compat->open;
    real_driver.control_xfer_cb = compat->control_xfer_cb;
    real_driver.xfer_cb = compat->xfer_cb;
    real_driver.sof = compat->sof;

    *count = 1;
    return &real_driver;
}
