; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_flags = 
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	
	-D ARDUINO_USB_MODE=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_USB_MSC_ON_BOOT=0
	-D ARDUINO_USB_DFU_ON_BOOT=0
	-D USE_TINYUSB=1
	-D CFG_TUD_AUDIO=1
	-D USB_INTERFACE_AUDIO=USB_INTERFACE_CUSTOM
	-D CFG_TUD_AUDIO_FUNC_1_DESC_LEN=136
	-D CFG_TUD_AUDIO_FUNC_1_N_AS_INT=1
	-D CFG_TUD_AUDIO_FUNC_1_CTRL_BUF_SZ=64
	-D CFG_TUD_AUDIO_ENABLE_EP_OUT=1
	-D CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX=512
	-D CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ=512
	-include include/usb_compat.h
    -I include
board_build.partitions = huge_app.csv
lib_deps = 
	https://github.com/pschatzmann/arduino-audio-tools.git
